project: Classification

name: ResNet

dir:
  train_dir: Datasets/Train
  test_dir: Datasets/Test
  meta_dir: Datasets/meta_data
  Exp: Exp

train:
  transform: False
  batch_size: 20
  cpu_alloc: 6
  Type: Train
  loader:
    flag: False
  image_size: 224
  dir: /media/mayank/0b40607e-7efc-4216-b12f-8bb86facfaed/Image_Net/ILSVRC/Data/CLS-LOC/train
  
test:
  transform: False
  batch_size: 20
  cpu_alloc: 6
  Type: Test
  loader:
    flag: False
  image_size: 224
  dir: /media/mayank/0b40607e-7efc-4216-b12f-8bb86facfaed/Image_Net/ILSVRC/Data/CLS-LOC/Val_class

target_transform: False
retrain: True

# Logging

log_interval_steps: 50
print_log_steps: 50
test_now: 500

# Parameters

image_size: 224
n_channels: 3
n_classes: 1000
lr: 0.0001
optimizer: Adam
lossf: CEL
cuda: True
seed: 2
rank: 5
epoch: 100
cummulative_batch_steps: 1
PreTrained: False

pretrained_model:
  checkpoint: 0_0_checkpoint.pth.tar
  checkpoint_info: 0_0_checkpoint_info.pth.tar

augmentation:
  brightness: 0.2
  contrast: 0.2
  saturation: 0.2
  hue: 0.2
