project: Classification

name: ResNet


    img_dir: /home/prantik/VOC2012/JPEGImages/
    tar_class: /home/prantik/VOC2012/SegmentationClass/
    tar_obj: /home/prantik/VOC2012/SegmentationObject/
    train: /home/prantik/VOC2012/ImageSets/Segmentation/train.txt
    val: /home/prantik/VOC2012/ImageSets/Segmentation/trainval.txt
    test: /home/prantik/VOC2012/ImageSets/Segmentation/val.txt


train:
  classification:
    transform: False
    batch_size: 20
    cpu_alloc: 6
    Type: Train
    loader:
      flag: False
    image_size: 224
    dir: /media/mayank/0b40607e-7efc-4216-b12f-8bb86facfaed/Image_Net/ILSVRC/Data/CLS-LOC/train
  segmentation:
    Type: Train
    loader:
      flag: False
    img_dir: /home/prantik/VOC2012/JPEGImages/
    tar_class: /home/prantik/VOC2012/SegmentationClass/
    tar_obj: /home/prantik/VOC2012/SegmentationObject/
    Train: /home/prantik/VOC2012/ImageSets/Segmentation/train.txt


  
test:
  classification:
    transform: False
    batch_size: 20
    cpu_alloc: 6
    Type: Test
    loader:
      flag: False
    image_size: 224
    dir: /media/mayank/0b40607e-7efc-4216-b12f-8bb86facfaed/Image_Net/ILSVRC/Data/CLS-LOC/Val_class
  segmentation:
    Type: Test
    loader:
      flag: False
    img_dir: /home/prantik/VOC2012/JPEGImages/
    tar_class: /home/prantik/VOC2012/SegmentationClass/
    tar_obj: /home/prantik/VOC2012/SegmentationObject/
    Test: /home/prantik/VOC2012/ImageSets/Segmentation/val.txt

target_transform: False
retrain: True

#prepare_metadata

prepare_metadata :
  unet :
    img_dir : /home/prantik/VOC2012/JPEGImages/
    tar_class : /home/prantik/VOC2012/SegmentationClass/
    tar_obj : /home/prantik/VOC2012/SegmentationObject/
    train : /home/prantik/VOC2012/ImageSets/Segmentation/train.txt
    val : /home/prantik/VOC2012/ImageSets/Segmentation/trainval.txt
    test : /home/prantik/VOC2012/ImageSets/Segmentation/val.txt

# Logging

log_interval_steps: 50
print_log_steps: 50
test_now: 500

# Parameters

image_size: 224
n_channels: 3
n_classes: 1000
lr: 0.0001
optimizer: Adam
lossf: CEL
cuda: True
seed: 2
rank: 5
epoch: 100
cummulative_batch_steps: 1
PreTrained: False

pretrained_model:
  checkpoint: 0_0_checkpoint.pth.tar
  checkpoint_info: 0_0_checkpoint_info.pth.tar

augmentation:
  brightness: 0.2
  contrast: 0.2
  saturation: 0.2
  hue: 0.2
